---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source_code: embed
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

data("instacart")
force(instacart)

```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart A

```{r, collapse=TRUE}
instacart %>% 
  count(aisle_id, aisle, sort = TRUE) %>% 
  filter(n > 10000) %>% 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar",
          colors = "viridis") %>% 
  layout(title = 'Number of Products with > 10,000 Orders by Aisle',
         xaxis = list(title = 'Aisle Name'), 
         yaxis = list(title = 'Number of Products Ordered'))
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart B

```{r, collapse = TRUE}
scatterplot = instacart %>% 
  count(department, name = "number_of_products") %>% 
  ggplot(aes(x = department, y = number_of_products)) +
  geom_point() +
  labs(
    title = "Number of Products Ordered by Department ",
    x = "Department",
    y = "Number of Prodcuts Ordered",
    caption =  "Data from Instacart"
  ) +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_y_continuous(labels = scales::comma)

ggplotly(scatterplot)
```

### Chart C

```{r, collapse=TRUE}
instacart  %>% 
  group_by(department, product_name) %>% 
  summarize(n_obs = n()) %>% 
  filter(n_obs > 5000) %>% 
  plot_ly(x = ~product_name, y = ~n_obs, color = ~department, type = "bar",
          colors = "viridis") %>% 
  layout(title = 'Top 10 Products Ordered',
         xaxis = list(title = 'Product Name'), 
         yaxis = list(title = 'Number of Products Ordered'))
```

